apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
      - name: install-custom-tools
        command: ["/bin/sh", "-c", "cp /tools/* /tmp/tools"]
        image: public.ecr.aws/r2h3l6e4/pingidentity/argocd-tools:0.0.1
