apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/eks-pingcloud-pingcl1
  password: machine-user-at-251360940232
  username: MEzQtT9vIQOcyWsxi988meiqCG78QMDJBRAVdUUiN0c=